apiVersion: v1
kind: Service
metadata:
  name: eks2-service
  namespace: ingress-nm
spec:
  selector:
    app: eks2  # Make sure your Deployment pods are labeled accordingly
  ports:
    - name: http
      protocol: TCP
      port: 80          # Ingress points to this port
      targetPort: 3000  # Your container listens here
  type: ClusterIP      # Suitable for ALB ingress – no need for NodePort
